repos:
  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier
        args:
          [
            --single-quote=true,
            --trailing-comma=none,
            --no-semi,
            --print-width=80,
            --tab-width=2,
          ]
